[package]
name = "kson_macro"
version = "0.1.0"
authors = ["theseriousadult <jack@gallabytes.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.14"
quote = "0.6"
proc-macro2 = "0.4"
